[package]
name = "mediastat"
version = "0.1.0"
authors = ["Sean Gallagher <seangllghr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mpris = "~2.0.0-rc2"
unicode-segmentation = "~1.7"
